### PR TITLE
test from NXP

### PR DESCRIPTION
**Pull request by hakehuang**

### CODE REVIEW

**Comment by hakehuang** [comment]
@PerMac  I change to json and there is no CI triggered still

**Comment by PerMac** [comment]
@hakehuang can you please rebase your PR? I merged to main a workflow that should do an auto-merge in case all requirements are fulfilled. Let's see if it'll work

**Comment by hakehuang** [comment]
> @hakehuang can you please rebase your PR? I merged to main a workflow that should do an auto-merge in case all requirements are fulfilled. Let's see if it'll work

updated. @PerMac

**Comment by PerMac** [comment]
can you please rebase one more time? I forgot to push labeler file.

**Comment by hakehuang** [comment]
> can you please rebase one more time? I forgot to push labeler file.

sure, rebased. but

```
Warning: The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions
Error: Resource not accessible by integration
```

**Pull request closed without merging**
